#!/bin/sh

set -e

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR

idn2 --version
echo "PASS: idn2 --version"

idn2 --help
echo "PASS: idn2 --help"

idn2 --version
idn2 --version|(! grep '()')
echo "PASS: idn2 --version"

man -P cat idn2
echo "PASS: man idn2"

# Make sure idn2 understands the locale is UTF-8, for the next test.
LC_ALL=C.UTF-8
export LC_ALL

idn2 --decode xn--rksmrgs-5wao1o
echo "PASS: idn2"
