#!/bin/sh

set -e

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR

idn2 --version
idn2 --help

idn2 --version|(! grep '()')
echo "PASS: idn2 libidn2 version"

man -P cat idn2
echo "PASS: man"
