#!/bin/sh

set -e

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR
cat <<EOF > libidn2test.c
#include <idn2.h>

int main(void)
{
  if (!idn2_check_version (IDN2_VERSION))
    return 1;

  return 0;
}
EOF

gcc -o libidn2test libidn2test.c `pkg-config --cflags --libs libidn2`
echo "PASS: gcc"
[ -x libidn2test ]
./libidn2test
echo "PASS: run"
man -P cat idn2_free
echo "PASS: man"
